repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.8
  hooks:
    # Run the linter.
    - id: ruff
- repo: local
  hooks:
    - id: custom-script-file
      name: custom-script-file
      entry: precommit.sh
      language: script
      types: [python]
      pass_filenames: false