services:
  discord-bot:
    image: discord-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./database.sqlite:/app/Crunchy-Patrol/database.sqlite
      - ./key.txt:/app/Crunchy-Patrol/key.txt
      - ./openai.txt:/app/Crunchy-Patrol/openai.txt
      - ./tenor.txt:/app/Crunchy-Patrol/tenor.txt