from enum import Enum


class EnemyType(str, Enum):
    MIND_GOBLIN = "MindGoblin"
    BOOBA_SLIME = "BoobaSlime"
    GARLIC_DOG = "GarlicDog"
    TABLE = "Table"
    GOOSE = "Goose"
    SHOPPING_CART = "ShoppingCart"
    NICE_GUY = "NiceGuy"
    YOUR_MOM = "YourMom"
    PIMPLE = "Pimple"
    CAT_DOG = "CatDog"
    MUSHROOM = "Mushroom"
    SCRIBBLER = "Scribbler"
    BROCOLI = "BroColi"
    DF_TANK = "DFTank"
    CUDDLES = "Cuddles"
    ELI = "Eli"
    HOMELESS_WOMAN = "HomelessWoman"
    CRACKACHU = "Crackachu"
    MOMMY = "Mommy"
    HOE = "Hoe"
    MIMIC = "Mimic"
    SCHOOL_BULLY = "SchoolBully"
    BONTERRY = "Bonterry"
    BONTERRY_KING = "BonterryKing"
    FAIRY = "Fairy"
    BOOMER = "Boomer"
    SAUSAGE_BUTCHER = "SausageButcher"

    DADDY_P1 = "Daddy_P1"
    DADDY_P2 = "Daddy_P2"

    WEEB_BALL = "WeebBall"
    WEEB_P1 = "Weeb_P1"
    WEEB_P2 = "Weeb_P2"
    WEEB_P3 = "Weeb_P3"
