services:
  devcontainer:
    image: devcontainer
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./../database.sqlite:/app/Crunchy-Bot/database.sqlite
      - ./../key.txt:/app/Crunchy-Bot/key.txt
      - ./../openai.txt:/app/Crunchy-Bot/openai.txt
      - ./../tenor.txt:/app/Crunchy-Bot/tenor.txt
    tty: true
    command: sleep infinity