on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: rsync -a /home/mara/actions-runner/_work/Crunchy-Bot/Crunchy-Bot/Dockerfile /home/mara/Bot/Crunchy-Bot/
      - run: rsync -a /home/mara/actions-runner/_work/Crunchy-Bot/Crunchy-Bot/docker-compose.yml /home/mara/Bot/Crunchy-Bot/
      - run: rsync -a /home/mara/actions-runner/_work/Crunchy-Bot/Crunchy-Bot/requirements.txt /home/mara/Bot/Crunchy-Bot/